services:
  php:
    build: .
    container_name: ${COMPOSE_PROJECT_NAME}_php
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME}_db
    platform: linux/amd64
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --sql-mode="" --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:1.25
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8083:80"
    depends_on:
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    platform: linux/amd64
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8082:80"
    depends_on:
      - db

volumes:
  db_data:
